site_name: "MediaManager Documentation"
theme:
  name: "material"
  logo: "assets/logo.svg"
  favicon: "assets/favicon.ico"
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path: ["."]

nav:
  - Welcome: index.md
  - Installation:
      - installation/README.md
      - Docker Compose: installation/docker.md
      - Nix Flakes [Community]: installation/flakes.md
  - Usage:
      - Importing existing media: importing-existing-media.md
  - Configuration:
      - configuration/README.md
      - Backend: configuration/backend.md
      - Authentication: configuration/authentication.md
      - Database: configuration/database.md
      - Download Clients: configuration/download-clients.md
      - Indexers: configuration/indexers.md
      - Scoring Rulesets: configuration/scoring-rulesets.md
      - Notifications: configuration/notifications.md
      - Custom Libraries: configuration/custom-libraries.md
      - Logging: configuration/logging.md
  - Advanced Features:
      - qBittorrent Category: advanced-features/qbittorrent-category.md
      - URL Prefix: advanced-features/url-prefix.md
      - Metadata Provider Configuration: advanced-features/metadata-provider-configuration.md
      - Custom port: advanced-features/custom-port.md
      - Follow symlinks in frontend files: advanced-features/follow-symlinks-in-frontend-files.md
      - Disable startup ascii art: advanced-features/disable-startup-ascii-art.md
  - Troubleshooting: troubleshooting.md
  - API Reference: api-reference.md
  - Screenshots: screenshots.md
  - Contributing to MediaManager:
      - Developer Guide: contributing-to-mediamanager/developer-guide.md
      - Documentation: contributing-to-mediamanager/documentation.md

extra:
  version:
    provider: mike
extra_css:
  - custom.css