[format]
line-ending = "lf"
quote-style = "double"

[lint]
# to be enabled: A, ANN, ARG, BLE, C90, CPY, D, DOC, DTZ, FBT, G, INP, INT, N, PERF, PIE, PL, PTH, RET, RSE, SLF, SIM, TC, TRY, UP
extend-select = [
    "ASYNC",
    "B",
    "C4", "COM",
    "E", "EM", "EXE",
    "F", "FA", "FAST", "FIX", "FLY", "FURB",
    "I", "ICN", "ISC",
    "LOG",
    "PGH", "PT", "PYI",
    "Q",
    "SLOT",
    "T10", "TD", "TID",
    "W",
    "YTT"
]

ignore = [
    # incompatible with formatter
    "COM812",
    # lines too long
    "E501",
    # currently a bug?! with providers and depends
    "FAST003",
]

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Path"]
